plugins {
    id 'base'
}

task npmInstall(type: Exec) {
    commandLine 'npm', 'install'
}

task npmBuild(type: Exec) {
    dependsOn npmInstall
    commandLine 'npx', 'vite', 'build'
}

task assembleDebug {
    dependsOn npmBuild
}

tasks.named('assemble') {
    dependsOn npmBuild
}

tasks.named('build') {
    dependsOn npmBuild
}
